prometheus:
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}

alertmanager:
  enabled: true
  alertmanagerSpec:
    configSecret: alertmanager-vpn-bot

grafana:
  enabled: true
