defaultRules:
  rules:
    etcd: false
    kubeControllerManager: false
    kubeProxy: false
    kubePrometheusGeneral: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}

alertmanager:
  enabled: true
  alertmanagerSpec:
    configSecret: alertmanager-vpn-bot

grafana:
  enabled: true
